apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: harshk777/keycloak-theme:v2
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin123"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres-service:5432/keycloak"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - name: http
          containerPort: 8080
        # --- YAHAN MAIN CHANGE HUA HAI ---
        volumeMounts:
        - name: theme-volume
          mountPath: /opt/keycloak/providers/
      volumes:
      - name: theme-volume
        hostPath:
          path: /home/ubuntu/keycloak-project/build-artifacts/
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: keycloak-ns
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
